# Generated by Django 6.0.6 on 2026-06-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documentation',
            field=models.FileField(blank=True, help_text='Project Report / Documentation PDF', null=True, upload_to='projects/docs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub Repository Link', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('individual', 'Individual Project'), ('team', 'Team Project')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.TextField(blank=True, help_text='Comma-separated names of team members (leave blank if Individual)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web_application', 'Web Application'), ('mobile_application', 'Mobile Application')], default='web_application', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text='Live Demo Link (Optional)'),
        ),
    ]
