# Generated by Django 6.0.6 on 2026-06-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_documentation_project_github_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web_application', 'Web Application'), ('mobile_application', 'Mobile Application'), ('both', 'Both')], default='web_application', max_length=50),
        ),
    ]
