# Generated by Django 6.0.6 on 2026-06-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web_application', 'Web Application'), ('mobile_application', 'Mobile Application')], default='web_application', max_length=50),
        ),
    ]
