# Generated by Django 6.0.6 on 2026-06-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('updates', 'Updates'), ('projects', 'Projects'), ('blogs', 'Blogs')], default='updates', max_length=20),
        ),
    ]
