# Generated by Django 6.0.6 on 2026-06-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('machine_learning', 'Machine Learning'), ('web_development', 'Web Development'), ('mobile_app', 'Mobile App'), ('data_science', 'Data Science'), ('updates', 'Updates & Logs')], default='updates', max_length=20),
        ),
    ]
