# Generated by Django 6.0.6 on 2026-07-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_post_options_remove_post_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Project Banner Image', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.TextField(blank=True, help_text='Comma-separated names of team members'),
        ),
    ]
